heat_template_version: 2016-04-08
description: 'Extra Post-Deployment Config, multiple'
parameters:
  server:
    type: string


# Note depends_on may be used for serialization if ordering is important
resources:
  CorpCertificateExtraPreConfig:
    type: all-pre-config/add-corp-certificate.yaml
    properties:
        server: {get_param: server}

  TunedProfilePreConfig:
    type: all-pre-config/tuned-profile.yaml
    properties:
        server: {get_param: server}

  SetupNestedKVMPreConfig:
    type: all-pre-config/setup-nested-kvm.yaml
    properties:
        server: {get_param: server}

  AllowInnoDBFilePerTablePreConfig:
    type: all-pre-config/allow-innodb-file-per-table.yaml
    properties:
        server: {get_param: server}

  SysctlTunablesPreConfig:
    type: all-pre-config/sysctl-tunables.yaml
    properties:
        server: {get_param: server}

outputs:
  deploy_stdout:
    value:
      list_join:
      - ''
      - - {get_attr: [CorpCertificateExtraPreConfig, deploy_stdout]}
        - {get_attr: [TunedProfilePreConfig, deploy_stdout]}
        - {get_attr: [SetupNestedKVMPreConfig, deploy_stdout]}
        - {get_attr: [AllowInnoDBFilePerTablePreConfig, deploy_stdout]}
        - {get_attr: [SysctlTunablesPreConfig, deploy_stdout]}
