parameter_defaults:
  CephStorageExtraConfig:
    ceph::profile::params::osd_journal_size: 1024
    ceph::profile::params::osd_pool_default_pg_num: 256
    ceph::profile::params::osd_pool_default_pgp_num: 256
    ceph::profile::params::osd_pool_default_size: 3
    ceph::profile::params::osd_pool_default_min_size: 1
    #ceph::profile::params::osds: {/srv/data: {}}
    ceph::profile::params::osds:
      /dev/sdb: {}
      /dev/sdc: {}
      /dev/sdd: {}
      /dev/sde: {}
      /dev/sdf: {}
      /dev/sdg: {}
      /dev/sdh: {}
