heat_template_version: 2016-04-08

description: >
  Does a global restart of the entire PCS cluster from controller-0

parameters:
  servers:
    type: json

resources:
  PcsClusterRestartExtraPostConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: scripts/pcs_cluster_restart.sh}

  PcsClusterRestartExtraPostDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      config: {get_resource: PcsClusterRestartExtraPostConfig}
      servers: {get_param: servers}
      actions: ['CREATE']
