heat_template_version: 2016-04-08

description: >
  Add root pubkey to authorized_keys on all nodes and enable RootLogin

parameters:
  servers:
    type: json
  ConfigDebug:
    default: false
    description: Enable puppet debugging
    type: boolean

resources:
  TrustedKeysExtraPostConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: scripts/add_trusted_keys.sh}

  TrustedKeysExtraPostDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      config: {get_resource: TrustedKeysExtraPostConfig}
      servers: {get_param: servers}
      actions: ['CREATE','UPDATE']
